# TUNæ¨¡å¼
vif_only: true
# IPv6
ipv6: true
# HTTPä»£ç†ç«¯å£
http_port: 6154
# Socks5ä»£ç†ç«¯å£
socks_port: 6153
# å…è®¸å¤–éƒ¨è¿æ¥
allow_external_connections: true
# åŠ«æŒ DNS æœåŠ¡å™¨
hijack_dns:
- '*:53'
# è‡ªå®šä¹‰MaxMindæ•°æ®åº“
geoip_db_url: https://raw.githubusercontent.com/sooyaaabo/KeleeOne/Loon/GeoData/Country-Masaiki.mmdb
asn_db_url: https://raw.githubusercontent.com/sooyaaabo/KeleeOne/Loon/GeoData/GeoLite2-ASN-P3TERX.mmdb
# ä»£ç†å»¶è¿Ÿæµ‹è¯•
proxy_latency_test_url: http://www.google.com/blank.html
# ç›´è¿å»¶è¿Ÿæµ‹è¯•
direct_latency_test_url: http://connectivitycheck.platform.hicloud.com/generate_204
dns:
  # DNS å¼•å¯¼å™¨ï¼šç”¨äºè§£æä¸Šæ¸¸DNS(DoTã€DoHã€DoQ)ï¼Œé»˜è®¤ system
  bootstrap:
    - system
  upstreams:
    # å›½å†…å…¬å…± DNS
    Domestic-DNS:
    - 223.5.5.5
    - 119.29.29.29
  # DNS è½¬å‘è§„åˆ™
  forward:
  - wildcard: # é€šé…ç¬¦è§„åˆ™
      match: "*"
      value: Domestic-DNS
policy_groups:
- external:
    name: SubName //æ›¿æ¢ä¸ºä½ çš„æœºåœºåç§°
    type: select
    urls: // ä¸‹æ–¹æ›¿æ¢ä¸ºä½ çš„è®¢é˜…é“¾æ¥
    - http://your-service-provider 
    filter: ''
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Egern-02.png
    hidden: false
- auto_test:
    name: Hong Kong
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|HKG|Hong|Hong Kong)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/HongKong.png
- auto_test:
    name: Macao
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡²ğŸ‡´|æ¾³é—¨|(\b(MO|MAC|Oman|Macau|Macao)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/Macao.png
- auto_test:
    name: TaiWan
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|å°æ¹¾|å°åŒ—|(\b(TW|TWN|Tai|Taiwan)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/Taiwan.png
- auto_test:
    name: Japan
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|JPN|Japan)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/Japan.png
- auto_test:
    name: South Korea
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ“|é¦–å°”|(\b(KR|KOR|Korea|Seoul)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/SouthKorea.png
- auto_test:
    name: Singapore
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|æ–°å›½|ç‹®|(\b(SG|SGP|Singapore)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/Singapore.png
- auto_test:
    name: United States
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|USA|United States|America)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/UnitedStates.png
- select:
    name: Remaining
    policies:
    - SubName
    flatten: true
    filter: ^(?=.*(.*))(?!.*((?i)ğŸ‡­ğŸ‡°|ğŸ‡²ğŸ‡´|ğŸ‡¹ğŸ‡¼|ğŸ‡¯ğŸ‡µ|ğŸ‡°ğŸ‡·|ğŸ‡¸ğŸ‡¬|ğŸ‡ºğŸ‡¸|é¦™æ¸¯|æ¾³é—¨|å°æ¹¾|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|éŸ©å›½|éŸ“|é¦–å°”|æ–°åŠ å¡|ç‹®|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|åˆ°æœŸ|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|ç¾¤|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|æ€»è®¡|é‡æ–°|è®¾ç½®ğŸ®|(\b(HK|HKG|Hong|Hong Kong|MO|MAC|Oman|Macau|Macao|TW|TWN|Tai|Taiwan|JP|JPN|Japan|KR|KOR|Korea|SG|SGP|Singapore|US|USA|United States|America|GAME|USE|USED|TOTAL|EXPIRE|EMAIL|Panel)\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag-Icon/UnitedNations.png
- select:
    name: Final
    policies:
    - Proxy
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Other-Icon/Final.png
- select:
    name: Proxy
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Egern-02.png
- select:
    name: OpenAI
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/ChatGPT.png
- select:
    name: AppleProxy
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Apple.png
- select:
    name: Google
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Google.png
- select:
    name: Microsoft
    policies:
    - DIRECT
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Microsoft.png
- select:
    name: GitHub
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/GitHub-01.png
- select:
    name: X
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Twitter-02.png
- select:
    name: Telegram
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Telegram-02.png
- select:
    name: TouTube
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/YouTube.png
- select:
    name: Netflix
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Netflix-02.png
- select:
    name: TikTok
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/TikTok-02.png    
- select:
    name: Emby
    policies:
    - Hong Kong
    - Macao
    - TaiWan
    - Japan
    - South Korea
    - Singapore
    - United States
    icon: https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/App-Icon/Conflux.png
rules:
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Direct.yaml
    policy: DIRECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Reject.yaml
    policy: REJECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/AI.yaml
    policy: OpenAI
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Github.yaml
    policy: GitHub
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Microsoft.yaml
    policy: Microsoft
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Google.yaml
    policy: Google
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Telegram.yaml
    policy: Telegram
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Twitter.yaml
    policy: X
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Emby.yaml
    policy: Emby
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/YouTube.yaml
    policy: YouTube
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Netflix.yaml
    policy: Netflix
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/TikTok.yaml
    policy: å›½é™…åª’ä½“
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/AppleProxy.yaml
    policy: AppleProxy
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/ProxyGFW.yaml
    policy: Proxy
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Apple.yaml
    policy: DIRECT
- rule_set:
    match: https://github.com/Repcz/Tool/raw/X/Egern/Rules/Lan.yaml
    policy: DIRECT
- geoip:
    match: CN
    policy: DIRECT
- default:
    policy: å…œåº•åˆ†æµ
mitm:
  enabled: true
modules:
- name: WebPage
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/WebPage.module
  enabled: true
- name: é“¶è¡Œ
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Bank.module
  enabled: true
- name: ä¸­å›½ç§»åŠ¨
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/ChinaMobile.module
  enabled: true
- name: Redirect
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Redirect.module
  enabled: true
- name: AppRaven
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/AppRaven.module
  enabled: true
- name: RevenueCat
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/RevenueCat.module
  enabled: true
- name: iTunes
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/iTunes.module
  enabled: false
- name: Google
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Google.module
  enabled: true
- name: QQ
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/QQ.module
  enabled: true
- name: å¾®ä¿¡
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/WeChat.module
  enabled: true
- name: å¤¸å…‹
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Quark.module
  enabled: true
- name: é˜¿é‡Œäº‘ç›˜
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Alipan.module
  enabled: true
- name: ç™¾åº¦ç½‘ç›˜
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/BaiduNetDisk.module
  enabled: true
- name: 123äº‘ç›˜
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/123Pan.module
  enabled: true
- name: è¿…é›·
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/ThunderCloudDisk.module
  enabled: true
- name: é«˜å¾·åœ°å›¾
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Amap.module
  enabled: true
- name: å°çº¢ä¹¦
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/RedNote.module
  enabled: true
- name: VVebo
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/VVebo.module
  enabled: true
- name: å¾®åš
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Weibo.module
  enabled: true
- name: å¾®åšè½»äº«ç‰ˆ
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Weibo_intl.module
  enabled: false
- name: QQéŸ³ä¹
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/QQMusic.module
  enabled: true
- name: ç½‘æ˜“äº‘éŸ³ä¹
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/NeteaseMusic.module
  enabled: true
- name: é…·æˆ‘éŸ³ä¹
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/KuwoMusic.module
  enabled: true
- name: å–œé©¬æ‹‰é›…
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Ximalaya.module
  enabled: true
- name: Listenify
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Listenify.module
  enabled: true
- name: è…¾è®¯è§†é¢‘
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/TencentVideo.module
  enabled: true
- name: çˆ±å¥‡è‰º
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/IQIYI.module
  enabled: true
- name: ä¼˜é…·è§†é¢‘
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/YoukuVideo.module
  enabled: true
- name: èŠ’æœTV
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/MangoTV.module
  enabled: true
- name: å“”å“©å“”å“©
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/BiliBili.module
  enabled: true
- name: è¤çŸ³äº‘è§†é¢‘
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Ezviz.module
  enabled: true
- name: XPTV
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/XPTV.module
  enabled: true
- name: CMS Adblocker
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/CMS_Adblock.module
  enabled: true
- name: é“è·¯12306
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Railway12306.module
  enabled: true
- name: æ·˜å®
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Taobao.module
  enabled: true
- name: é—²é±¼
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Goofish.module
  enabled: true
- name: äº¬ä¸œ
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Jingdong.module
  enabled: true
- name: ä»€ä¹ˆå€¼å¾—ä¹°
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Zhidemai.module
  enabled: true
- name: èœé¸Ÿ
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Cainiao.module
  enabled: true
- name: é…·å®‰
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/CoolApk.module
  enabled: true
- name: ITä¹‹å®¶
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/IThome.module
  enabled: true
- name: çŸ¥ä¹
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Zhihu.module
  enabled: true
- name: Soul
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/Soul.module
  enabled: true
- name: MyBlockAds
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/MyBlockAds.module
  enabled: true
- name: å¢¨é±¼å»å¼€å±
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/StartUp.module
  enabled: true
- name: å¹¿å‘Šæ‹¦æˆªåˆé›†
  url: https://raw.githubusercontent.com/sooyaaabo/Egern/main/module/AdsBlocker.module
  enabled: true
- name: BoxJS
  url: https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.surge.sgmodule
  enabled: true
- name: Script Hub
  url: https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.surge.sgmodule
  enabled: true
- name: Sub Store
  url: https://raw.githubusercontent.com/Peng-YM/Sub-Store/master/config/Surge.sgmodule
  enabled: true
